#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


# Down
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Up
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-scale $SCRIPTPATH/wallpaper.png
fi

# Polybar
if [ -x "$(command -v polybar)" ]; then
  ln -sfn $SCRIPTPATH/polybar ~/.config/polybar
  polybar -r &
fi

# Rofi
if [ -x "$(command -v rofi)" ]; then
  ln -sfn $SCRIPTPATH/rofi ~/.config/rofi 
fi

# Dunst
if [ -x "$(command -v dunstr)" ]; then
  dunst &
fi

# Bat
if [ -x "$(command -v bat)" ]; then
  ln -sfn $SCRIPTPATH/bat ~/.config/bat
  bat cache --build
fi
